name: Build TvAnti UnityPackages

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:

  unity-2022-2:
    name: "2022.2"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create UnityPackage
        shell: bash
        run: |
          set -euo pipefail

          mkdir -p "release/2022.2"

          tar -czf \
            "release/2022.2/TvAnti2022.2.unitypackage" \
            package/

      - name: Upload 2022.2
        uses: actions/upload-artifact@v4
        with:
          name: TvAnti-2022.2
          path: "release/2022.2/TvAnti2022.2.unitypackage"


  unity-2023-3:
    name: "2023.3"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create UnityPackage
        shell: bash
        run: |
          set -euo pipefail

          mkdir -p "release/2023.3"

          tar -czf \
            "release/2023.3/TvAnti2023.3.unitypackage" \
            package/

      - name: Upload 2023.3
        uses: actions/upload-artifact@v4
        with:
          name: TvAnti-2023.3
          path: "release/2023.3/TvAnti2023.3.unitypackage"


  unity-6-lts:
    name: "6 LTS"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create UnityPackage
        shell: bash
        run: |
          set -euo pipefail

          mkdir -p "release/6 LTS"

          tar -czf \
            "release/6 LTS/TvAnti6 LTS.unitypackage" \
            package/

      - name: Upload 6 LTS
        uses: actions/upload-artifact@v4
        with:
          name: TvAnti-6-LTS
          path: "release/6 LTS/TvAnti6 LTS.unitypackage"


  unity-6-2-lts:
    name: "6.2 LTS"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create UnityPackage
        shell: bash
        run: |
          set -euo pipefail

          mkdir -p "release/6.2 LTS"

          tar -czf \
            "release/6.2 LTS/TvAnti6.2 LTS.unitypackage" \
            package/

      - name: Upload 6.2 LTS
        uses: actions/upload-artifact@v4
        with:
          name: TvAnti-6.2-LTS
          path: "release/6.2 LTS/TvAnti6.2 LTS.unitypackage"


  package-all:
    name: Package All Versions
    needs:
      - unity-2022-2
      - unity-2023-3
      - unity-6-lts
      - unity-6-2-lts

    runs-on: ubuntu-latest

    steps:
      - name: Download 2022.2
        uses: actions/download-artifact@v4
        with:
          name: TvAnti-2022.2
          path: "TvAnti/2022.2"

      - name: Download 2023.3
        uses: actions/download-artifact@v4
        with:
          name: TvAnti-2023.3
          path: "TvAnti/2023.3"

      - name: Download 6 LTS
        uses: actions/download-artifact@v4
        with:
          name: TvAnti-6-LTS
          path: "TvAnti/6 LTS"

      - name: Download 6.2 LTS
        uses: actions/download-artifact@v4
        with:
          name: TvAnti-6.2-LTS
          path: "TvAnti/6.2 LTS"

      - name: Create final ZIP
        shell: bash
        run: |
          set -euo pipefail

          zip -qr TvAnti-all.zip TvAnti

      - name: Upload final ZIP
        uses: actions/upload-artifact@v4
        with:
          name: TvAnti-all
          path: TvAnti-all.zip
